### ISSUE TITLE
Add "advanced view" as alternative to new ordering interface

### ISSUE THREAD

**Issue by julian-george** [ospreyelm/AnalyticPiano#110]
Likely involves coding new django `Form` that uses the same block text fields as before, with more complex cleaning functions to convert the results into the new M2M relationship.

**Comment by ospreyelm** [comment]
The block text fields can be used as an alternative procedure for the Add widget. These were robustly coded; it will be a simple task to get the ordered list of exercise IDs (e.g. EA00AA) or playlists IDS (e.g. PA00AA) from here and append it to the list of exercises for a playlist or the list of playlists for a course.

**Comment by ospreyelm** [comment]
done
