### ISSUE TITLE
Better implementation of ordering field

### ISSUE THREAD

**Issue by julian-george** [ospreyelm/AnalyticPiano#112]
Instead of hacking together the field with extensive and inflexible (and hacky) changes to the template, create a custom widget with custom javascript that would speed things up, improve flexibility, and allow for more intuitive behavior like drag and drop.

**Comment by julian-george** [comment]
This is a good start: https://stackoverflow.com/a/1816992/7385274

**Comment by ospreyelm** [comment]
fixed or no longer relevant
